# Generated by Django 3.1.4 on 2020-12-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201231_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='us',
        ),
    ]
