# Generated by Django 3.1.4 on 2020-12-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20201231_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idc',
            field=models.SmallIntegerField(default=0),
        ),
    ]
