# Generated by Django 3.1.4 on 2021-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_profile_idc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='chelovek.jpg', null=True, upload_to='profile/'),
        ),
    ]
