# Generated by Django 3.1.4 on 2021-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20210102_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(blank=True, default='images/chelovek.jpg', null=True, upload_to='profile/'),
        ),
    ]
